### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by NetOperatorWibby** [Jellyfishboy/trado#4]
* Is Trado production-ready?
* If it *is* production ready, how do I run it?
* Is there a specific stack required for optimum use?

**Comment by Jellyfishboy** [comment]
Trado is currently going through the last amendments and tests. It will have its first public release in the next two weeks; if you would to receive updates on its release, please signup at [www.trado.io](trado.io).

Over the coming days I will put together a getting started guide for local development installation as well as AWS, Heroku and Digital Ocean for production

As for the stack, the platform has been tested on both MySQL and PostgreSQL databases along with several Rack servers (Puma, Thin, WEBrick Unicorn), so there is no specific stack in order to use the platform. However, I would advise using Unicorn or Puma alongside PostgreSQL for optimal use.

**Comment by NetOperatorWibby** [comment]
Sweet, thanks!
